//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETSystemCliente.UPCNETServiceCursoAlumno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno")]
    public interface UPCNETServiceCursoAlumno {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse getCursoAlumnoById(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdRespons" +
            "e")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse> getCursoAlumnoByIdAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/helloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse hello(UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/helloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/helloResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse> helloAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnosRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse getCursoAlumnos(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnosRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnosResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse> getCursoAlumnosAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse editAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editAlumnoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse> editAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoAlumnoReporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string alumnoApellidoField;
        
        private string alumnoNombreField;
        
        private string cursoNombreField;
        
        private string idAlumnoField;
        
        private string idCursoField;
        
        private string profesorApellidoField;
        
        private string profesorNombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alumnoApellido {
            get {
                return this.alumnoApellidoField;
            }
            set {
                this.alumnoApellidoField = value;
                this.RaisePropertyChanged("alumnoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string alumnoNombre {
            get {
                return this.alumnoNombreField;
            }
            set {
                this.alumnoNombreField = value;
                this.RaisePropertyChanged("alumnoNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cursoNombre {
            get {
                return this.cursoNombreField;
            }
            set {
                this.cursoNombreField = value;
                this.RaisePropertyChanged("cursoNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string profesorApellido {
            get {
                return this.profesorApellidoField;
            }
            set {
                this.profesorApellidoField = value;
                this.RaisePropertyChanged("profesorApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string profesorNombre {
            get {
                return this.profesorNombreField;
            }
            set {
                this.profesorNombreField = value;
                this.RaisePropertyChanged("profesorNombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class alumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string correoField;
        
        private string direccionField;
        
        private int dniField;
        
        private bool dniFieldSpecified;
        
        private int edadField;
        
        private bool edadFieldSpecified;
        
        private string idAlumnoField;
        
        private string idApoderadoField;
        
        private string idCategoriaField;
        
        private string nombreField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dniSpecified {
            get {
                return this.dniFieldSpecified;
            }
            set {
                this.dniFieldSpecified = value;
                this.RaisePropertyChanged("dniSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edadSpecified {
            get {
                return this.edadFieldSpecified;
            }
            set {
                this.edadFieldSpecified = value;
                this.RaisePropertyChanged("edadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string idApoderado {
            get {
                return this.idApoderadoField;
            }
            set {
                this.idApoderadoField = value;
                this.RaisePropertyChanged("idApoderado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class alumnoCurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int delegadoField;
        
        private double efField;
        
        private bool efFieldSpecified;
        
        private double epField;
        
        private bool epFieldSpecified;
        
        private string idAlumnoField;
        
        private string idCursoField;
        
        private int inasistenciasField;
        
        private double pc1Field;
        
        private bool pc1FieldSpecified;
        
        private double pc2Field;
        
        private bool pc2FieldSpecified;
        
        private int retiradoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int delegado {
            get {
                return this.delegadoField;
            }
            set {
                this.delegadoField = value;
                this.RaisePropertyChanged("delegado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ef {
            get {
                return this.efField;
            }
            set {
                this.efField = value;
                this.RaisePropertyChanged("ef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool efSpecified {
            get {
                return this.efFieldSpecified;
            }
            set {
                this.efFieldSpecified = value;
                this.RaisePropertyChanged("efSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double ep {
            get {
                return this.epField;
            }
            set {
                this.epField = value;
                this.RaisePropertyChanged("ep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool epSpecified {
            get {
                return this.epFieldSpecified;
            }
            set {
                this.epFieldSpecified = value;
                this.RaisePropertyChanged("epSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int inasistencias {
            get {
                return this.inasistenciasField;
            }
            set {
                this.inasistenciasField = value;
                this.RaisePropertyChanged("inasistencias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double pc1 {
            get {
                return this.pc1Field;
            }
            set {
                this.pc1Field = value;
                this.RaisePropertyChanged("pc1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pc1Specified {
            get {
                return this.pc1FieldSpecified;
            }
            set {
                this.pc1FieldSpecified = value;
                this.RaisePropertyChanged("pc1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pc2 {
            get {
                return this.pc2Field;
            }
            set {
                this.pc2Field = value;
                this.RaisePropertyChanged("pc2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pc2Specified {
            get {
                return this.pc2FieldSpecified;
            }
            set {
                this.pc2FieldSpecified = value;
                this.RaisePropertyChanged("pc2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int retirado {
            get {
                return this.retiradoField;
            }
            set {
                this.retiradoField = value;
                this.RaisePropertyChanged("retirado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoById", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idCurso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idAlumno;
        
        public getCursoAlumnoByIdRequest() {
        }
        
        public getCursoAlumnoByIdRequest(string idCurso, string idAlumno) {
            this.idCurso = idCurso;
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoByIdResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte @return;
        
        public getCursoAlumnoByIdResponse() {
        }
        
        public getCursoAlumnoByIdResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnos", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnosRequest {
        
        public getCursoAlumnosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnosResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] @return;
        
        public getCursoAlumnosResponse() {
        }
        
        public getCursoAlumnosResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumnoCurso arg0;
        
        public setCursoAlumnoRequest() {
        }
        
        public setCursoAlumnoRequest(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumnoCurso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoAlumnoResponse {
        
        public setCursoAlumnoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumno arg0;
        
        public editAlumnoRequest() {
        }
        
        public editAlumnoRequest(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumno arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editAlumnoResponse {
        
        public editAlumnoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCursoAlumnoChannel : UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCursoAlumnoClient : System.ServiceModel.ClientBase<UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno>, UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno {
        
        public UPCNETServiceCursoAlumnoClient() {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoById(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest request) {
            return base.Channel.getCursoAlumnoById(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte getCursoAlumnoById(string idCurso, string idAlumno) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest();
            inValue.idCurso = idCurso;
            inValue.idAlumno = idAlumno;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoByIdAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest request) {
            return base.Channel.getCursoAlumnoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdResponse> getCursoAlumnoByIdAsync(string idCurso, string idAlumno) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdRequest();
            inValue.idCurso = idCurso;
            inValue.idAlumno = idAlumno;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.hello(UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest();
            inValue.name = name;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.helloAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloResponse> helloAsync(string name) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.helloRequest();
            inValue.name = name;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnos(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest request) {
            return base.Channel.getCursoAlumnos(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] getCursoAlumnos() {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest();
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnosAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest request) {
            return base.Channel.getCursoAlumnosAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosResponse> getCursoAlumnosAsync() {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnosRequest();
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request) {
            return base.Channel.setCursoAlumno(request);
        }
        
        public void setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumnoCurso arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).setCursoAlumno(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request) {
            return base.Channel.setCursoAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumnoCurso arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).setCursoAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.editAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest request) {
            return base.Channel.editAlumno(request);
        }
        
        public void editAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).editAlumno(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.editAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest request) {
            return base.Channel.editAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoResponse> editAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.alumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.editAlumnoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).editAlumnoAsync(inValue);
        }
    }
}
